### ISSUE TITLE
No command like Show Process View

### ISSUE THREAD

**Issue by ugurozturk** [weinand/vscode-processes#1]
Updated to VS Code 1.19.0 and checked the command. I can't see it and tried to find if this is an extension but nothing.

**Comment by hugoj-goncalves** [comment]
You could've finished reading the changelog.
![image](https://user-images.githubusercontent.com/10927715/34038085-2f538c18-e172-11e7-85ac-bbbad3bb9222.png)

**Comment by rdiazlugo** [comment]
These are the steps to run.

```
git clone https://github.com/weinand/vscode-processes
cd vscode-processes
npm install
npm run package
```

**Comment by weinand** [comment]
After building the extension as a VSIX with the steps from below, you have to use VS Code's "Install from VSIX..." command to install the extension.

**Comment by ro-savage** [comment]
Would be good to have this in the readme

**Comment by weinand** [comment]
done!
